// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2sHGZgJpv2lkyTO8_rgEv6BMjaNHWAPY',
    appId: '1:73601045868:web:cd654db0017a3e0a354f49',
    messagingSenderId: '73601045868',
    projectId: 'smartmed-20c2a',
    authDomain: 'smartmed-20c2a.firebaseapp.com',
    storageBucket: 'smartmed-20c2a.firebasestorage.app',
    measurementId: 'G-BS0Y0KDS33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzXrMeL6Z4q-ITr-J3Av4wUaq9jJFgs6Y',
    appId: '1:73601045868:android:c690e38405ab7f9a354f49',
    messagingSenderId: '73601045868',
    projectId: 'smartmed-20c2a',
    storageBucket: 'smartmed-20c2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD29_xCC8OIYu5FXWHbvWrF5StZ-I_OnQ',
    appId: '1:73601045868:ios:4167edf6f293291e354f49',
    messagingSenderId: '73601045868',
    projectId: 'smartmed-20c2a',
    storageBucket: 'smartmed-20c2a.firebasestorage.app',
    iosBundleId: 'com.example.smartMed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD29_xCC8OIYu5FXWHbvWrF5StZ-I_OnQ',
    appId: '1:73601045868:ios:4167edf6f293291e354f49',
    messagingSenderId: '73601045868',
    projectId: 'smartmed-20c2a',
    storageBucket: 'smartmed-20c2a.firebasestorage.app',
    iosBundleId: 'com.example.smartMed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2sHGZgJpv2lkyTO8_rgEv6BMjaNHWAPY',
    appId: '1:73601045868:web:556d0f32e9d76ec8354f49',
    messagingSenderId: '73601045868',
    projectId: 'smartmed-20c2a',
    authDomain: 'smartmed-20c2a.firebaseapp.com',
    storageBucket: 'smartmed-20c2a.firebasestorage.app',
    measurementId: 'G-3ZSXXPJKQJ',
  );
}
